version: '3.8'
services:
  n2sql:
    container_name: n2sql
    image: n2sql:${TAG:-latest}
    build:
      context: n2sql
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    env_file:
      - .env
    environment:
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SQL_SERVER=${SQL_SERVER}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USERNAME=${SQL_USERNAME}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - ENGINE=${ENGINE}
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
      - MODEL_NAME=${MODEL_NAME}